---
- name: Instalacion de Grid infrastructure 19c
  hosts: all
  gather_facts: false
  become: true
  environment:
    PATH: /usr/bin:usr/
  pre_tasks:

  - name: Instalacion Grid | Crea grupo en memoria para los nodos 1
    add_host:
      hostname: "{{ item }}"
      ansible_host: "{{ hostvrs[item].ansible_host }}"
      groups: nodo1
    loop: "{{ groups['cluster'] }}"
    when: item == item[:-1] + '1'

  - name: Instalacion Grid | Crea grupo en memoria para los nodos 2
    add_host:
      hostname: "{{ item }}"
      ansible_host: "{{ hostvrs[item].ansible_host }}"
      groups: nodo2
    loop: "{{ groups['cluster'] }}"
    when: item == item[:-1] + '2'

  roles:
    - grid_instalacion
...
